name: update-constants
on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install regression
      run: npm i regression
    - name: Run script
      # run: node index.js
    - name: Check for changes
      run: git status
    - name: Stage changed files
      run: git add -A
    - name: Commit changed files
      env:
        EMAIL_SECRET: ${{ secrets.EMAIL }}
        NAME_SECRET: ${{ secrets.NAME }}
      run: git config user.email $EMAIL_SECRET
      run: git config user.name $NAME_SECRET
      run: git commit -m "Updating rate.json"
    - name: Push code to master
      run: git push origin master