name: update-constants
on: 
  [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install regression
      run: npm i regression
    - name: Run script
      run: node index.js
    - name: Setup SSH Key
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
      run: git remote set-url origin https://$USERNAME:$TOKEN@github.com/$USERNAME/SekaiCutoffRate.git
    - name: Check for changes
      run: git status
    - name: Stage changed files
      run: git add -A
    - name: Commit changed files
      run: |
        git config user.email liupotor4@gmail.com
        git config user.name "potor"
        git commit -m "Updating rate.json"
    - name: Push code to master
      run: git push origin HEAD:master