name: update-constants
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 4,12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install regression
      run: npm i regression
    - name: Run script
      run: node index.js
    - name: Check for changes
      run: git status
    - name: Stage changed files
      run: git add -A
    - name: Commit changed files
      run: git config user.email "liupotor4@gmail.com"
      run: git config user.name "Potor"
      run: git commit -m "Updating rate.json"
    - name: Push code to master
      run: git push origin master